<?php

namespace flowcode\enlace\view;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-08-26 at 20:52:34.
 */
class PlainViewTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var PlainView
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $viewData["data"] = "test";
        $this->object = new PlainView($viewData);
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers flowcode\enlace\view\PlainView::__construct
     * @covers flowcode\enlace\view\PlainView::render
     */
    public function testRender_testDefault_testOk() {
        $this->object->render();
        $this->expectOutputString('test');
    }

}
