<?php

namespace flowcode\enlace\view;

use flowcode\enlace\Enlace;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-08-26 at 20:52:34.
 */
class ViewTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var View
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        Enlace::set("view", array(
            "path" => __DIR__ . "/aux"
        ));
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers flowcode\enlace\view\View::__construct
     * @covers flowcode\enlace\view\View::render
     */
    public function testRender_testWihoutLayout_testOk() {
        $this->expectOutputString('test');
        $viewData["simple-view-data"] = "test";
        $viewName = "layout-root/simpleview";
        $this->object = new View($viewData, $viewName, FALSE);
        $this->object->render();
    }

    /**
     * @covers flowcode\enlace\view\View::render
     */
    public function testRender_oneLevelLayout_testOk() {
        $this->expectOutputString("sectionview|layout-one|layout-root");
        $viewData["data"] = "sectionview";
        $viewName = "layout-root/layout-one/section";

        $this->object = new View($viewData, $viewName);
        $this->object->render();
    }

    /**
     * @covers flowcode\enlace\view\View::render
     */
    public function testRender_twoLevelLayout_testOk() {
        $this->expectOutputString("sectionview|layout-two|layout-one|layout-root");
        $viewData["data"] = "sectionview";
        $viewName = "layout-root/layout-one/layout-two/section";
        $aa = new View($viewData, $viewName);
        $aa->render();
    }
    
    /**
     * @covers flowcode\enlace\view\View::render
     */
    public function testRender_oneLevelLayoutNotHierarchy_testOk() {
        $this->expectOutputString("sectionview|layout-root-other");
        $viewData["data"] = "sectionview";
        $viewName = "layout-root-other/layout-one/section";
        $aa = new View($viewData, $viewName);
        $aa->render();
    }

}
