<?php

namespace flowcode\wing\mvc;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-08-16 at 21:06:11.
 */
class KernelTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var Kernel
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Kernel();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers flowcode\wing\mvc\Kernel::handleRequest
     * @todo   Implement testHandleRequest().
     */
    public function testHandleRequest() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers flowcode\wing\mvc\Kernel::getRequest
     * @todo   Implement testGetRequest().
     */
    public function testGetRequest() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers flowcode\wing\mvc\Kernel::shutdown
     * @todo   Implement testShutdown().
     */
    public function testShutdown() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers flowcode\wing\mvc\Kernel::getConfigurationFiles
     * @todo   Implement testGetConfigurationFiles().
     */
    public function testGetConfigurationFiles() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers flowcode\wing\mvc\Kernel::setConfigurationFiles
     * @todo   Implement testSetConfigurationFiles().
     */
    public function testSetConfigurationFiles() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers flowcode\wing\mvc\Kernel::addConfigurationFile
     * @todo   Implement testAddConfigurationFile().
     */
    public function testAddConfigurationFile() {
        $before = count($this->object->getConfigurationFiles());
        $this->object->addConfigurationFile("/log");
        $after = count($this->object->getConfigurationFiles());
        $this->assertEquals($before + 1, $after);
    }

    /**
     * @covers flowcode\wing\mvc\Kernel::setLoginController
     * @todo   Implement setLoginController().
     */
    public function testSetLoginController() {
        $this->object->setLoginController("\\flowcode\\wing\\controller\\DefaultController");
    }

}
