<?php

namespace flowcode\enlace\controller;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-08-26 at 20:52:34.
 */
class BaseControllerTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var BaseController
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new BaseController();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers flowcode\enlace\controller\BaseController::setIsSecure
     * @covers flowcode\enlace\controller\BaseController::isSecure
     * 
     */
    public function testSetIsSecure_testSecureTrue_testOk() {
        $this->object->setIsSecure(true);
        $this->assertTrue($this->object->isSecure());
    }

    /**
     * @covers flowcode\enlace\controller\BaseController::addPermission
     * @covers flowcode\enlace\controller\BaseController::canAccess
     * 
     */
    public function testCanAccess_canAccess_testOk() {

        $user["roles"] = array(
            "admin" => array(
                "permissions" => array("random-permission"))
        );

        $this->object->addPermission("random-permission");

        $this->assertTrue($this->object->canAccess($user));
    }

    /**
     * @covers flowcode\enlace\controller\BaseController::addPermission
     * @covers flowcode\enlace\controller\BaseController::canAccess
     * 
     */
    public function testCanAccess_cannotAccess_testOk() {

        $user["roles"] = array(
            "admin" => array(
                "permissions" => array("fail-permission"))
        );

        $this->object->addPermission("random-permission");

        $this->assertFalse($this->object->canAccess($user));
    }

}
