<?php

namespace flowcode\enlace\http;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-01-04 at 20:35:52.
 */
class HttpRequestBuilderTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var HttpRequestBuilder
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new HttpRequestBuilder();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers flowcode\enlace\http\HttpRequestBuilder::buildFromRequestUrl
     */
    public function testBuildFromRequestUrl_defaultController_ok() {
        $requestedUrl = "/home";
        $httpRequest = HttpRequestBuilder::buildFromRequestUrl($requestedUrl);
        $this->assertEquals("home", $httpRequest->getControllerName());
    }

    /**
     * @covers flowcode\enlace\http\HttpRequestBuilder::buildFromRequestUrl
     */
    public function testBuildFromRequestUrl_defaultControllerLangES_ok() {
        \flowcode\enlace\Enlace::set("available-lang", array("es", "en"));
        $requestedUrl = "/es/home";
        $httpRequest = HttpRequestBuilder::buildFromRequestUrl($requestedUrl);
        $this->assertEquals("home", $httpRequest->getControllerName());
    }

    /**
     * @covers flowcode\enlace\http\HttpRequestBuilder::buildFromRequestUrl
     */
    public function testBuildFromRequestUrl_withGetParams_ok() {
        $requestedUrl = "/home?id=1";
        $httpRequest = HttpRequestBuilder::buildFromRequestUrl($requestedUrl);
        $this->assertEquals("home", $httpRequest->getControllerName());
    }

    /**
     * @covers flowcode\enlace\http\HttpRequestBuilder::buildFromRequestUrl
     */
    public function testBuildFromRequestUrl_parseParams_ok() {
        $requestedUrl = "/home/index/id/1/name/jorge";
        $httpRequest = HttpRequestBuilder::buildFromRequestUrl($requestedUrl);
        $this->assertEquals("home", $httpRequest->getControllerName());
        $this->assertEquals("1", $httpRequest->getParameter("id"));
        $this->assertEquals("jorge", $httpRequest->getParameter("name"));
    }

}
